services:
  pd-contract-test-consumer:
    build:
      context: .
      target: production
    image: pd-contract-test-consumer
    container_name: pd-contract-test-consumer
    environment:
      APPINSIGHTS_CLOUDROLE: pd-contract-test-consumer-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
